### ISSUE TITLE
counterscript - new implementation needed?

### ISSUE THREAD

**Issue by mgeerdsen** [wellcometrust/workflow#100]
The so called counterscript collects information on exported processes (date of export, access license, possible deletion in DDS etc.) and regularly generates CSV files. It currently evaluates the exported METS files in the export location. The current implementation will not be usable in AWS anymore, so this might need a re-implementation if still needed.

**Comment by pollecuttn** [comment]
The CSV file is still needed. From a colleague (Branwen):

I use it to identifiy records that need dlnks (although I’m not doing that at the moment because of new material not appearing in the Viewer).

I tend to access it directly by typing in a URL http://wt-winnipeg/Counterscript/api/csv/withinactive/YYYY-MM-DD/YYYY-MM-DD because that is what was in Joao’s instructions, although I remember Rioghnach did show me that I could get to it in Goobi too (apparently Joao objected to having to log in to Goobi!)

I definitely need information about access (restricted files, closed, etc) because I need to exclude those from my list for dlnks. I would also need to know if anything has been deleted, as I might need to remove a dlnk.

Just to add that of course I also need the export dates, so I know which records still need their dlnks.

**Comment by pollecuttn** [comment]
ie the file is used to identify records in another system, Sierra, to update catalogue records appropriately after digitisation is completed.

**Comment by rsehr** [comment]
Currently the counterscript application checks once a day, if something was changed on the exported mets file. It checks, if a new record was exported, an exiting record was updated or deleted. The information are stored in a database. When you access http://wt-winnipeg/Counterscript/, the data is taken from this database. To do this, the script searches for files at the network share on //wellcomeit.com/shares/LIB_WDL_DDS/LIB_WDL_DDS_METS/x/x/x/x/

As the new export is no longer written into the filesystem and is not access-able directly by goobi any more, this solution won't work in the new environment.

Is there a way for us to ask the archive service to return the needed information to us? We need either directly the mets files of everything that was changed between 2 dates or the information as a xml and/or json. Currently we store filename, b-number, material code, access status, license, player permission , status (new, updated, deleted), creation date, modification date, deletion date of each mets file.

**Comment by jtweed** [comment]
I've talked to the Digital Production team and we've agreed that we need a way to produce the CSV files for additions and updates, but that we can handle deletions manually as they don't happen very often.

Given that, I think there is enough information in the normal Goobi database to produce these exports? And that there's then no need to look at the METS files for changes?

**Comment by rsehr** [comment]
At the moment we don't have all information available, but this can be implemented. The only exception is the part of deletions because when a process is deleted, its gone completely

**Comment by jtweed** [comment]
What information is not currently in the main Goobi database? I thought that's where the METS info was stored?

As above, deletions not being there we can work around outside of Goobi.

**Comment by rsehr** [comment]
At the moment, we don't have any history of changed access conditions or other relevant metadata. Also we don't save when and how often the file was exported. 
We have only the knowledge that a process was exported to the player and about the current metadata

**Comment by jtweed** [comment]
But surely that's enough? The CSV can just represent the current state?

**Comment by opaetzel** [comment]
What Robert meant was that we have no information about changed access conditions or other relevant metadata at all without the CounterScript. We just talked about it in the team and will change the export plugin to save all needed information to the database on each export. So the only thing missing would be deletions - which is OK.

**Comment by jtweed** [comment]
Thanks @opaetzel

**Comment by rsehr** [comment]
the new counterscript was implemented and is intalled on AWS
