### ISSUE TITLE
implementation of a migration tool

### ISSUE THREAD

**Issue by mgeerdsen** [wellcometrust/workflow#101]
DB and files need to be changed and migrated, especially be split up between EFS and S3

Workflows will need changes and it has to be defined which files can be dropped and which need migration

**Comment by opaetzel** [comment]
The general plan looks like this:

1. export db metadata from winnipeg-goobi to each corresponding process dir.
2. use s3-sync to copy all data from goobi/metadata/ to s3
3. after the first sync, stop the production on winnipeg and make a last incremental update with s3-sync
4. export users, projects and rulesets from winnipeg
5. import users, projects and rulesets on AWS
6. import processes in AWS goobi (this includes a mapping to the new workflow templates on AWS)
7. resume production on AWS

The needed steps to accomplish this will be  put in their own issues.
