### ISSUE TITLE
Authentication needs to be set up for Goobi in AWS

### ISSUE THREAD

**Issue by mgeerdsen** [wellcometrust/workflow#103]
Goobi is currently on-premises and only supports authentication via LDAP.

We are migrating Goobi to AWS and don't have capacity to to add another authentication mechanism.

My understanding is LDAP is not a good security choice over the public internet (even if encrypted via SSL).

So options are limited to providing some network restricted (still using SSL!) LDAP endpoint to the migrated service in AWS. 

We could: 

- Provide that via VPN / Endpoint service connection to an internal (on-premise) LDAP service. (edited) 
- Have Azure AD federate with Cognito allowing us to provide an LDAP endpoint over a private network connection.

We'll need to ensure that Goobi has the correct public/private endoint split with the load balancer in the public subnet, app in the private alongside whatever is providing the LDAP endpoint.

**Comment by kenoir** [comment]
Callback authentication from the storage service to Goobi will be performed via JWT encoded in the URL requested for callback, which will then be decrypted and used for authentication when the callback is fulfilled.

**Comment by mgeerdsen** [comment]
@opaetzel will look into using OAUTH 2
