### ISSUE TITLE
implement S3 upload for digitised material

### ISSUE THREAD

**Issue by mgeerdsen** [wellcometrust/workflow#104]
needs to be implemented like or added to the EP lambda, as described in https://github.com/wellcometrust/platform/tree/master/docs/rfcs/007-goobi_upload

**Comment by rsehr** [comment]
the goal of this ticket is to have an image upload to existing processes. The uploaded zip files need to be picked up, sorted into the correct process folder and extracted

**Comment by opaetzel** [comment]
this was tested locally and works fine
