### ISSUE TITLE
memory leak when using JP2000 images (especially for export with PREMIS data)

### ISSUE THREAD

**Issue by mgeerdsen** [wellcometrust/workflow#106]
@opaetzel has already improved the situation, but had to open https://github.com/dbmdz/imageio-jnr/issues/10 as well

**Comment by H-Bluhm** [comment]
workaround has been built and tested locally and on winslow, remains to be installed

**Comment by mgeerdsen** [comment]
The workaround for the premis export has also been deployed to winnipeg and all ingest steps have been activated again.
mets editor workaround can be handled in a new issue

**Comment by opaetzel** [comment]
There has been a fix for this in the imageio-openjpeg repo: https://github.com/dbmdz/imageio-jnr/issues/10
I will investigate if this new version fixes our problem and depending on that re-add the dependency to Goobi.

**Comment by opaetzel** [comment]
This has been sorted out and I don't see any memory leak in my tests. We will re-add the imageio jp2000 bridge to Goobi once it has been published to maven central.
