### ISSUE TITLE
Winnipeg: check storage

### ISSUE THREAD

**Issue by opaetzel** [wellcometrust/workflow#110]
- [x] collect data on storage usage
- [x] check workflow templates for deletion steps and add where needed
- [x] identify files for potential deletion
- [x] actually delete old data if needed

**Comment by mgeerdsen** [comment]
storage usage on winnipeg should be re-analyzed, to have a basis for possible further workflow improvements and the migration tool(s)

**Comment by mgeerdsen** [comment]
a background job is running on winnipeg to collect data about storage usage

**Comment by mgeerdsen** [comment]
added checkboxes to issue

**Comment by mgeerdsen** [comment]
## storage usage by file type and goobi sub directory

### by file type

| file        | size [TB] |
| ----------- |-----------|
| jpg         | 3.8       |
| tif         | 1.7       |
| mp?         | 2.9       |
| jp2         | 2.7   |
| xml         | 2.8   |
| zip         | 0.5   |
| meta.xml    | 0.018 |
| txt         | 0.003 |


### by folder

| folder         | size [TB] |
| -------------- |-----------|
| *_jpg          |  3.36     |
| *_jp2          |  0.49     |
| *_media        |  7.22     |
| master_*_media |  4  	     |
| *_alto         |  2.3      |
| source         |  1.5      |
| import         |  0.002    |
| ocr		 |  2.3      |
| images         |  12.2     |
| validation     |  0.08     |
| taskmanager    |  0.013    |

**Comment by mgeerdsen** [comment]
There are about 3 TB of data in the Wellcome_Film project for processes that have already passed the SDB ingest. This sounds like something that can potentially be deleted

**Comment by pollecuttn** [comment]
@mgeerdsen Ashley says: 

> Christy has given the go ahead to clean up the Wellcome Films from Goobi storage. @matthias can you confirm how this clean up will be done?
https://wellcome.slack.com/archives/C6LLC2V8Q/p1558688187004700

**Comment by mgeerdsen** [comment]
those films have now been successfully deleted

**Comment by pollecuttn** [comment]
@mgeerdsen Can this be closed now?

**Comment by mgeerdsen** [comment]
the following templates do not include jpeg deletion:
- Wellcome_Film
- Published_born_digital
- 19_century_import
- Manuscript_ingest_TIFF
- Proquest_EEB
- Wellcome_Audio
- UK_MOH_Reports

We will now check if all of those should actually include it.

**Comment by mgeerdsen** [comment]
I added the deletion steps to the following templates:

- Manuscript_ingest_TIFF
- Proquest_EEB

the others don't have jpegs that should be deleted
