### ISSUE TITLE
Archivist export: add possibility to ingest .tar.gz  bags

### ISSUE THREAD

**Issue by opaetzel** [wellcometrust/workflow#118]
The zip format should still be possible

**Comment by opaetzel** [comment]
This is implemented and will be available on AWS with the next redeploy.

**Comment by pollecuttn** [comment]
@opaetzel Thanks, Oliver. When will the next redeploy be?

**Comment by opaetzel** [comment]
Whenever we want. I could do it right now. But we would also need to configure Goobi to create .tar.gz files instead of .zip. Also I don't know if the archive service that is running right now already supports .tar.gz.

**Comment by pollecuttn** [comment]
@opaetzel Okay, let's discuss at stand up

**Comment by pollecuttn** [comment]
@opaetzel Wellcome is ready to switch on tar.gz support for the storage service now.
https://wellcome.slack.com/archives/C6LLC2V8Q/p1552558913017200

**Comment by opaetzel** [comment]
I have configured winnipeg and the AWS goobi instance to use tar.gz from now on. We will see if it behaves as we would like it and can then close this ticket
