### ISSUE TITLE
Migrate all workflows

### ISSUE THREAD

**Issue by opaetzel** [wellcometrust/workflow#121]
All workflows should be transferred from winnipeg to AWS.

- [ ] create generic tiff workflow (replacement for Digitisation_on_Demand_TIFF, Manuscript_ingest_TIFF, Recipe_Books_TIFF, Visual_Arts_TIFF)
- [ ] create generic jp2 workflow (replacement for Archive_digitisation_JP2, Digitisation_on_Demand_JP2, Proquest_EEB, Visual_Arts_JP2)
- [ ] migrate video workflow (Wellcome_Film)
- [ ] migrate audio workflow (Wellcome_Audio)

**Comment by mgeerdsen** [comment]
All current production workflow should be added to the AWS instance. This is a check for completeness of all components and allows for complete end to end testing.

**Comment by rsehr** [comment]
- [ ] create generic tiff workflow (replacement for Digitisation_on_Demand_TIFF, Manuscript_ingest_TIFF, Recipe_Books_TIFF, Visual_Arts_TIFF)
- [ ] create generic jp2 workflow (replacement for Archive_digitisation_JP2, Digitisation_on_Demand_JP2, Proquest_EEB, Visual_Arts_JP2)
- [ ] migrate video workflow (Wellcome_Audio)
- [ ] migrate audio workflow (Wellcome_Film)

**Comment by kenoir** [comment]
@H-Bluhm have copied these bullet points to the top so they appear on the project board.

**Comment by mgeerdsen** [comment]
reminder, when video/audio takes too much work... we should check back on that before doing any changes

**Comment by rsehr** [comment]
this isue has been replaced by separate issues for each template
