### ISSUE TITLE
Implement import plugin for goobi users, projects and rulesets

### ISSUE THREAD

**Issue by opaetzel** [wellcometrust/workflow#139]
See #137 for the corresponding export

- [x] ldap information
- [x] docket information + files
- [x] ruleset information + files
- [x] projects
- [x] user groups
- [x] user
- [x] assigned user groups
- [x] assigned projects

**Comment by rsehr** [comment]
- [ ] ldap information
- [ ] docket information + files
- [ ] ruleset information + files
- [ ] projects
- [ ] user groups
- [ ] user
- [ ] assigned user groups
- [ ] assigned projects- [ ]

**Comment by mgeerdsen** [comment]
We also need to make sure that projects (filegroups) also need to be adapted during import, as we have no need for the SDB group anymore but will need OBJECTS
