### ISSUE TITLE
testing proposal

### ISSUE THREAD

**Issue by opaetzel** [wellcometrust/workflow#151]
The following is to be done by intranda
- [ ] manually create processes on winslow in different states and migrate them. Check all processes manually 
- [ ] migrate 10 random processes from each project and check if the mapping works for each workflow
- [ ] 1000 random processes for first mass test. Make random checks for correctness
- [ ] create buckets for each year and migrate 100 random processes from each year-bucket. Make random checks in each bucket

Wellcome should also check the resulting data as ingested in the the archive service for several of the above test processes.

Afterwards the following should be done by Wellcome and should reflect the usual usage of Goobi:
- [ ] continue work with several migrated processes on AWS (provided by intranda) and check data exported from Goobi
- [ ] create and work with several new processes created from migrated templates (using several projects)
The last point includes the use of different upload mechanisms as well (browser vs. S3)

**Comment by mgeerdsen** [comment]
closing as this has been put into several new issues
