### ISSUE TITLE
manual migration testing

### ISSUE THREAD

**Issue by mgeerdsen** [wellcometrust/workflow#153]
- [x] migrate templates to winslow
- [x] check and complete mapping configuration if needed for these
- [x] manually create processes from these templates
- [x] migrate processes to AWS
- [x] work with and finish processes in AWS

**Comment by H-Bluhm** [comment]
Found Issue in the JPEG conversion with Files starting with '.' , added filter to Script on Shellserver to avoid.

**Comment by opaetzel** [comment]
The migrated processes have been tested. What still needs to be done is testing processes created on AWS. There are already tickets for that.
