### ISSUE TITLE
migration test: 10 random processes from each project

### ISSUE THREAD

**Issue by mgeerdsen** [wellcometrust/workflow#154]
migrate 10 random processes from each project on winnipeg and check if the mapping works for each workflow

**Comment by rsehr** [comment]
sql query to get 10 random processes from each project:

`
SELECT 
    prozesseId, proj.titel AS project
FROM
    (SELECT 
        *,
            @row:=IF(projekteId = @projekteId, @row, 0) + 1 AS rn,
            @projekteId:=projekteId
    FROM
        (SELECT 
        *, RAND() AS trand
    FROM
        prozesse) t1, (SELECT @row:=0, @projekteId:='') tm2
    ORDER BY projekteId , trand) t2
        LEFT JOIN
    projekte proj ON t2.projekteId = proj.projekteId
WHERE
    rn <= 10
`
