### ISSUE TITLE
migration testing: random sample for each year of process creation

### ISSUE THREAD

**Issue by mgeerdsen** [wellcometrust/workflow#156]
create buckets for each year and migrate 100 random processes from each year-bucket. Make random checks in each bucket

**Comment by rsehr** [comment]
Query to get random processes for each year:

`SELECT 
    prozesseId, DATE_FORMAT(erstellungsdatum, '%Y')
FROM
    (SELECT 
        *,
            @row:=IF(DATE_FORMAT(erstellungsdatum, '%Y') = @createDate, @row, 0) + 1 AS rn,
            @createDate:=DATE_FORMAT(erstellungsdatum, '%Y')
    FROM
        (SELECT 
        *, RAND() AS trand
    FROM
        prozesse) t1, (SELECT @row:=0, @createDate:='') tm2
    ORDER BY DATE_FORMAT(erstellungsdatum, '%Y') , trand) t2
WHERE
    rn <= 100;`

**Comment by mgeerdsen** [comment]
processes have been migrated to AWS and checking needs to be continued on a per year basis
