### ISSUE TITLE
goobi docker container uses up available storage

### ISSUE THREAD

**Issue by mgeerdsen** [wellcometrust/workflow#167]

**Comment by mgeerdsen** [comment]
This mainly appears to have its origin in temporary files being created and deleted inside the container. This has now been changed for the Goobi container. Files are now written to EBS.

Creation of logfiles is still to be checked.

**Comment by mgeerdsen** [comment]
Application specific log configuration is overwritten in the docker container, so that no log files are created anymore.

Harvester/shellserver/ITM should also be updated in more or less the same way.

**Comment by mgeerdsen** [comment]
@H-Bluhm could you verify that the problem appears to be solved for the Goobi container now?

**Comment by H-Bluhm** [comment]
Unsuccessfully tried to induce excessive memory use in the container after the change.
