### ISSUE TITLE
check handling of DDS/Premis export steps during migration

### ISSUE THREAD

**Issue by mgeerdsen** [wellcometrust/workflow#171]
Changing "Export to DDS" -> "Export with PREMIS data" could lead to bags being created withough PREMIS data, as one might think this has already been included when the step is "done".
We should also check the handling of processes that have both steps again (might already be handled correctly).

**Comment by rsehr** [comment]
changed the configuration to remove the old 'Export to DDS' step and add a new step 'Export with PREMIS data'
