### ISSUE TITLE
Update Bagit export on Winnipeg

### ISSUE THREAD

**Issue by H-Bluhm** [wellcometrust/workflow#179]
This includes updating the Premis export plugin, switching the .jar for the bagit step, updating the archive ingest plugin and updating the wellcome rest plugin.

For processing of Multiple Manifestations the archive-mmo-check step plugin as well as a working callback are needed.

All Processes which have not completed the bagit export have to run through the premis export and bagit step again.

**Comment by mgeerdsen** [comment]
prepared... will be applied 20190807
