### ISSUE TITLE
Modify terraform-modules to allow multiple FS mounts

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/workflow#18]
In order to allow task manager workers to use EBS, while other services needing access to shared metadata use EFS, we will need to modify the existing terraform-modules

Currently https://github.com/wellcometrust/terraform-modules allows only one mount per launch configuration for clusters intended to run ECS, we must allow mounting both (at least) one EFS and one EBS volume.

**Comment by pollecuttn** [comment]
@kenoir Should this be on the Q3 project board? https://github.com/wellcometrust/workflow/projects/2

**Comment by mgeerdsen** [comment]
This has been completed by @alicefuzier in https://github.com/wellcometrust/terraform-modules/pull/69
