### ISSUE TITLE
archive ingest: winslow/staging - unauthorized when talking to api-stage

### ISSUE THREAD

**Issue by mgeerdsen** [wellcometrust/workflow#190]
`Failed to ingest bag, status codes was 401 response body was {"@context":"https://api.wellcomecollection.org/storage/v1/context.json","errorType":"http","httpStatus":"401","label":"Unauthorized","description":"Unauthorized","type":"Error"}`

**Comment by opaetzel** [comment]
I removed the scope from the token request, Matthias will check if this helps
