### ISSUE TITLE
Migration testing: Test 25% random processes

### ISSUE THREAD

**Issue by opaetzel** [wellcometrust/workflow#193]

**Comment by rsehr** [comment]
we checked all ingests and found some smaller issues, mostly related to the latest changes regarding the archive ingest:

* 19_century, Chemist_and_druggist: the task DDS API Call is missing
* Archive backlog: change order of Edit METS and Image conversion JPG
* Digitisation_on_Demand, Genetics_Books_Project, Glasgow_Crichton_3rd_Party_ftp, Glasgow_Gartnaval_3rd_Party_ftp, LMA_3rd_Party_ftp, Medieval_Manuscripts, RAMC_Books: delete task PDF creation
* Migration_project: add tasks Image removal, jpeg deletion after 90 days delay and 15 days delay
* Wellcome Audio: add task Image removal at the end
