### ISSUE TITLE
Migration testing: Test 50% random processes

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/workflow#194]

**Comment by mgeerdsen** [comment]
AWS Goobi has been updated and most data has already been wiped. Afterwards the slightly enhanced synctool (#200 ) will be used for the migration.

The migrated data should then also be used for testing the work in Goobi again etc.

**Comment by mgeerdsen** [comment]
sync was started on Friday (late afternoon) and currently about a quarter of the processes to be transferred have been uploaded

**Comment by rsehr** [comment]
the sync is finished now. But when we try to start the import, we run into a browser timeout because the listing of the process data on s3 takes to long. We will need to change the plugin to run it asynchronous in the background
