### ISSUE TITLE
Create ECR repos in terraform, refer to URIs 

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/workflow#2]
We should be able to create the ECR repos in terraform and simply generate the app/nginx urls seen here:

https://github.com/wellcometrust/workflow/blob/master/service.tf#L8

See: 

https://github.com/wellcometrust/platform/blob/master/catalogue_api/terraform/ecr.tf
https://github.com/wellcometrust/platform/blob/master/catalogue_api/terraform/services.tf#L16

**Comment by mgeerdsen** [comment]
As discussed with @kenoir we will put the URLs into variables at first.

**Comment by mgeerdsen** [comment]
fixed in 753f4d23b69d975b516e662ff62ed9f5227439f0 (referenced the wrong issue unfortunately)
