### ISSUE TITLE
Migration testing: Test 100% processes

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/workflow#201]
- [x] sync of files to AWS finished
- [x] export workflows on winnipeg finished
- [x] sync of exported files to AWS finished
- [x] testing of samples of migrated data on AWS finished

**Comment by mgeerdsen** [comment]
Process data is now being synced on top of the 50% set. Afterwards we will re-sync the XML files with the DB information from winnipeg, as there are still some DB changes outstanding.

**Comment by mgeerdsen** [comment]
The sync started 2019-10-08 and finished 2019-10-26, 8 processes could not be transferred initially, but could be finished in a few minutes by another run.
