### ISSUE TITLE
Expire objects in S3 export-bagit buckets where appropriate

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/workflow#212]
In order to keep storage costs down and ensure that temporary storage does not grow indefinitely we should expire objects in:

wellcomecollection-workflow-export-bagit
wellcomecollection-workflow-export-bagit-stage

After 4 days (or about as long as the storage service will ever buffer requests).

**Comment by mgeerdsen** [comment]
I will add this as well, as I am just working on changing versioning/lifecycling for various buckets wrt #238

**Comment by mgeerdsen** [comment]
old bags have indeed been deleted from both buckets
