### ISSUE TITLE
Implement OIDC Authentication in Cloud Goobi

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/workflow#218]
In order to authenticate easily as an Azure AD registered application, Goobi should support [OpenID Connect (OIDC)](https://en.wikipedia.org/wiki/OpenID_Connect). 

- [x] Redirect User to OIDC auth endpoint
- [x] Parse and verify OIDC JWT
- [x] Log-in user
- [x] Test with real users

**Comment by kenoir** [comment]
Required for #103

**Comment by opaetzel** [comment]
This is implemented and already deployed to AWS
