### ISSUE TITLE
AWS Goobi should redirect when logging in

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/workflow#226]

**Comment by opaetzel** [comment]
this is done and will be available on AWS with the next redeploy

**Comment by pollecuttn** [comment]
@opaetzel When will the next redeploy be? I'm concerned that if this is in 'Done' we'll forget it's not actually in place if there hasn't been a redeployment. I'd prefer that things go into 'Done' only when they're deployed and therefore available.

**Comment by opaetzel** [comment]
@pollecuttn I would have redeployed right away, but we are currently importing the 100% test. We will pause the import once a day for redeploys, so this will be available either this late afternoon or Monday. I will put the issue back in todo for now

**Comment by opaetzel** [comment]
this is now deployed to AWS
