### ISSUE TITLE
verify verification step after receiving callback

### ISSUE THREAD

**Issue by mgeerdsen** [wellcometrust/workflow#235]
For #177 checks where added after receiving a callback. This needs some checking (see winnipeg id:316389):

- [x] The log message should be easier to parse
- [x] Verify that the correct images folder is being used for checking against storage manifest
- [x] Verify that certain files are potentially ignored as for the bagit creation.
- [x] Verify that step is set to error when an error is being reported.

**Comment by pollecuttn** [comment]
@mgeerdsen Can this be closed? All the checkboxes are ticked

**Comment by mgeerdsen** [comment]
As Robert moved this to Done in November this can be closed.
