### ISSUE TITLE
TaskManager: finish dockerization and add to ECS

### ISSUE THREAD

**Issue by mgeerdsen** [wellcometrust/workflow#38]
Basic instance should be added to run in ECS, single plugins handled in upcoming issues

**Comment by mgeerdsen** [comment]
Since communication via the the ALB was not feasable, ITM and Goobi are now running in the same ECS service with linked containers on one instance. This appears to be working fine so far and will be tested further. Changes have now been pushed to https://github.com/wellcometrust/workflow/tree/add_itm_task

**Comment by mgeerdsen** [comment]
Communication from Goobi to the ITM is working without problems and tasks are starting. This issue can be closed when the code is merged to master together with the shellserver changes probably.

**Comment by mgeerdsen** [comment]
As the communication has not been working bi-directionally using docker links, a switch has been made to a new infrastructure (https://github.com/wellcometrust/workflow/pull/59). When everything is up and running we need to re-test end to end and the ticket can be closed.

**Comment by kenoir** [comment]
Can this be closed now?

**Comment by mgeerdsen** [comment]
Works as expected and an example workflow is available as Sample_workflow_jpeg-conversion
