### ISSUE TITLE
Goobi S3 storage: Adjust OCR taskmanager plugin

### ISSUE THREAD

**Issue by opaetzel** [wellcometrust/workflow#54]

**Comment by opaetzel** [comment]
We are not sure if this is still needed, as most OCR is created by the Internet Archive. @jtweed could you find out / let us know if you still need OCR done by the intranda service. If not, this one can be closed.

**Comment by jtweed** [comment]
Hi @opaetzel. I've done a bit of digging on this and it looks like we can certainly de-prioritise this. We'd like the option of being able to use the OCR service in the future, for archives, but it's not something that needs to happen before the migration to AWS.

**Comment by opaetzel** [comment]
not needed anymore
