### ISSUE TITLE
Prepare IA workflow

### ISSUE THREAD

**Issue by mgeerdsen** [wellcometrust/workflow#60]
- [x] dockerize Harvester
- [x] add Harvester to ECS
- [x] add IA Download Plugin to ITM image
- [x] add ALTO conversion to ITM/shellserver
- [x] add MetsCreation Goobi plugin to Goobi image
- [x] prepare InternetArchiveParser for AWS usage (@opaetzel )
- [x] add InternetArchiveParser
- [x] prepare workflow template(s)

**Comment by opaetzel** [comment]
The configuration files for the added plugins are still missing.

**Comment by mgeerdsen** [comment]
The harvester is already running in ECS (https://github.com/wellcometrust/workflow/tree/add_harvester), but needs a bit more configuration and testing to be fully integrated in an automated workflow.
