### ISSUE TITLE
Move Editorial_Photography workflow to AWS

### ISSUE THREAD

**Issue by H-Bluhm** [wellcometrust/workflow#71]
Modify Plugins/scripts relevant to Editorial_Photography workflow to work on AWS and with S3 storage.

This includes issues #26 #34 #46 #48 and #56

**Comment by H-Bluhm** [comment]
Deployed plugin to create process to AWS.

**Comment by opaetzel** [comment]
I deployed everything up until the TandemVault step to AWS. This is ready for testing now.
