### ISSUE TITLE
Callback from archive service fails

### ISSUE THREAD

**Issue by mgeerdsen** [wellcometrust/workflow#73]
Archive service callbacks are failing currently, e.g.
`{"description": "Callback failed for: 9f03d442-58b7-4021-872e-d84bbefd01eb (Connection failed.)"`

Very probably caused by ingress filtering on the LB

**Comment by opaetzel** [comment]
There is only one issue left - the archive service should accept the `204 - no content` status code from Goobi

**Comment by opaetzel** [comment]
The archive service now accepts 204 status codes
