### ISSUE TITLE
Internal Goobi Integration

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/workflow#76]
Test new storage service integration with Goobi running on pl-winslow.

**Comment by mgeerdsen** [comment]
this needs a full update of goobi including all plugins and itm on winslow, which can be prepared in advance to actually testing the ingest

**Comment by mgeerdsen** [comment]
Everything has been installed on winslow. Callbacks are not yet making it through to Goobi, but S3 uploads and ingest requests have been successful

**Comment by kenoir** [comment]
pl-winslow is currently available - we need to request firewall updates for wt-winnipeg
