### ISSUE TITLE
Goobi export plugins: split off bagit export to be able to run old export as well

### ISSUE THREAD

**Issue by mgeerdsen** [wellcometrust/workflow#78]

**Comment by mgeerdsen** [comment]
This has been installed on winslow, waiting to be tested there when Preservica is back up

**Comment by pollecuttn** [comment]
@mgeerdsen A test instance of Preservica is available again so please go ahead with your test

**Comment by mgeerdsen** [comment]
I was able to ingest to Preservica again and will check the result tomorrow. When #82 is fixed we can try a full workflow including Preservica and the new storage system.
