### ISSUE TITLE
Implement update mechanism for bags (needed for multiple manifestations)

### ISSUE THREAD

**Issue by mgeerdsen** [wellcometrust/workflow#87]
For multiple manifestations the archive service should be checked for the existence of an object with the same b-number.  If one exists the content should be listed and used to create a (partial) update bag which adds the current manifestation.

Adaptions to the new rfc will be needed in the following plugins:
- [x] bagit creation
- [x] premis export
- [x] archive ingest

**Comment by H-Bluhm** [comment]
To be tested further when Archivist API is updated

**Comment by mgeerdsen** [comment]
@H-Bluhm This should be ready for you to re-visit and test next week.

**Comment by H-Bluhm** [comment]
Tested on AWS with new storage service API.
