### ISSUE TITLE
Test Editorial Photography update workflow

### ISSUE THREAD

**Issue by opaetzel** [wellcometrust/workflow#91]
This ticket is for testing the editorial photography update workflow. This will first be done locally and later on AWS

**Comment by mgeerdsen** [comment]
decided to test it in a joint session and do that after TandemVault problem has been solved

**Comment by mgeerdsen** [comment]
blocked by #115

**Comment by H-Bluhm** [comment]
All plugins and the workflow as a whole have been tested and all Issues that appeared have been resolved.
