### ISSUE TITLE
configure Lurawave Linux cli in shellserver

### ISSUE THREAD

**Issue by mgeerdsen** [wellcometrust/workflow#98]

**Comment by H-Bluhm** [comment]
wrapper script is done, needs to be added to shellserver and installed

**Comment by H-Bluhm** [comment]
installed and tested on AWS,
some .tif are not converted to valid JPEG2000 (Part 1) and instead appear to be JPEG2000 (Part 2)

**Comment by H-Bluhm** [comment]
Tested again with  images taken from workflow 32899_c_b28722504 (id:169284 ; project Digitisation_on_Demand) on winnipeg:
  
 * compression on winnipeg led to valid JPEG2000 (Part 1) images.
 * compression on AWS led to invalid JPEG2000 (Part 1) which file identifies as JPEG2000 (Part 2) (process lurawaveTest_2; id:9193)
 * stripping metadata from the tif images with convert -strip before compressing them with lurawave led to valid JPEG2000 (Part 1) images (process lurawaveTest_3; id:9194)


As of now it is unclear whether a subset of the metadata is responsible for this or if all have to be removed to ensure compression to a valid JPEG2000 (Part 1) image using the linux commandline binary

**Comment by mgeerdsen** [comment]
Digging deeper it turns out that the embedded ICC profile is causing this behaviour. JPEG2000 Part 1 only accepts input type profiles, while the embedded Adobe RGB profile is considered a display device profile. Stripping the ICC profile completely for testing results in a Part 1 jp2 file being created.
This is also explained at http://dlib.org/dlib/may11/vanderknijff/05vanderknijff.html

The Linux cli version is 2.1.20.10 and as observed here and in the paper is simply creating a part 2 image in this case. The current production system behaves differently, by changing to input profile, which resembles the behaviour described for version 2.1.22.0 in the paper.

This all brings us actually to http://blog.wellcomelibrary.org/2011/05/icc-profiles-and-lurawave/

**Comment by mgeerdsen** [comment]
evaluate options:

- prepare images to change the type of the color profile so that lurawave creates part 1
- equivalent usage of OpenJPEG or kakadu

**Comment by pollecuttn** [comment]
@mgeerdsen Has the evaluation been done? Is there anything to add here?

**Comment by mgeerdsen** [comment]
indeed, after evaluation we decided to implement the first option in the already existing wrapper for the lurawave binary. Work hast started on that.

**Comment by H-Bluhm** [comment]
wrapper has been reworked and tested on AWS, the profile is successfully replaced
